//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOKUdemy.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urun()
        {
            this.tbl_satis = new HashSet<tbl_satis>();
        }
    
        public int Id { get; set; }
        public string Urunad { get; set; }
        public Nullable<int> Markaid { get; set; }
        public Nullable<int> Katid { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        public virtual Tbl_Marka Tbl_Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_satis> tbl_satis { get; set; }
    }
}
