//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOKUdemy.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_satis
    {
        public int Id { get; set; }
        public Nullable<int> urunid { get; set; }
        public Nullable<int> musteriid { get; set; }
        public Nullable<int> personelid { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual Tbl_Müsteri Tbl_Müsteri { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
        public virtual Tbl_Urun Tbl_Urun { get; set; }
    }
}
